name: Test accessing vault secrets.ACCESS_TOKEN

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: verify runner can reach vault
      id: curl-vault
      run: |
        echo "::set-output name=response::$(curl https://ldx-mapi.lighthouse.va.gov/vault:8200)"
    - name: check response 
      run: |
        echo "response back was: ${{ steps.curl-vault.outputs.response }} !"